### ISSUE TITLE
Error when running predection on another test file

### ISSUE THREAD

**Issue by ArijRB** [BKHMSI/deep-diacritization#3]
Hello, 
First of all thank you for sharing your code. I managed to reproduce the evaluation on tashkeela test set but when I tried to use D3 model on another test file from another dataset I got an error. The segmentation is done using the same config for the test file. Is there any specific per-processing that needs to be done before prediction? I check your paper but I couldn't find it. This is the error message I got :

```
Traceback (most recent call last):
  File "predict_d3.py", line 116, in <module>
    diacritized_lines = predictor.predict_mv()
  File "predict_d3.py", line 87, in predict_mv
    char_vote_haraka  += [y_gen_diac[seg_idx][t_idx][c_idx]]
IndexError: index 13 is out of bounds for axis 0 with size 13
```
Any help is appreciated :)

**Comment by BKHMSI** [comment]
Hi, I am happy to hear that you were able to reproduce our results. 
There shouldn't be any other pre-processing needed. The problem seems to be that you are using a different `T_w` (which is the maximum number of characters in a word) than what you have specified in the config file during segmentation. Can you share with me your configuration file you are using for your new dataset to help pinpoint your problem?

**Comment by ArijRB** [comment]
Thank you for your quick answer. I kept the same config for the test file this is it : 

```
segment:
  stride: 2
  window: 20
  min-window: 1
  export-map: true
```
It works when I change the` max-word-len` for predictions. 
Do you think to improve the prediction on my data, I need to re-train the model with new T_w? The T_w you used depends on the train data?

**Comment by BKHMSI** [comment]
Yeah, it seems that your dataset has words with more characters than the default `13` in the config file. 

Concerning re-training, the `T_s` and `T_w` hyperparameters were tuned based on the Tashkeela dev set. So other values might prove to be better in your case. You should also note that the pre-trained models we made available were trained on the cleaned version of Tashkeela, which is a Classical Arabic dataset, so it won't work as well with MSA or other forms of Arabic. Thus you might need to re-train the model with another dataset that matches the form (and domain) of your test file.

**Comment by munael** [comment]
Note: `T_s` and `T_w` do not affect the structure of the model and so may be given different values during train/eval. The change will affect prediction time slightly, but the model should still give you useful output.

`T_w` should be safe to change, but changing `T_s` may affect task performance.

**Comment by ArijRB** [comment]
Thank you for your answers. Yeah, from what I understood in your paper the T_w doesn't affect the model weights. I am using the model (d3) on MSA, the problem is that there is no other public dataset than tashkeela as far as I know.
