### ISSUE TITLE
Training the model from scratch

### ISSUE THREAD

**Issue by Hamza5** [BKHMSI/deep-diacritization#4]
Hello,

First, thank you for releasing the code of your paper.

Second, I am trying to train your D3 model from scratch using my own partition of the Tashkeela dataset. Until now, I could pass all the processing steps, but I am stuck in the training step.
When I run `scripts/train.sh d3` script as mentioned in your `ReadMe.md` file, I get an error of `FileNotFoundError: [Errno 2] No such file or directory: './models/Tashkeela-D2/tashkeela-d2.pt'`  in your `train_d3.py`.
I know that this means that the pre-trained model doesn't exist, but do I really need a pre-trained model? I want to start the training from scratch, I don't want that my training gets affected by any other previous data that you have used.
So what is the solution please?

**Comment by BKHMSI** [comment]
Hi Hamza,

Thanks for your interest in our paper.

In order to train the D3 model you need to first train the D2 model on your data, since D3 uses the weights of the encoders and character embeddings learned from D2. Those weights are then frozen, and only the decoder and the classifier are trained using the `train_d3.py` script. 

In short, follow the steps to train the D2 model as in the `ReadMe.md`, change the path in the `configs/config_d3.yaml` of the `resume` variable to point to your D2 checkpoint, then run `scripts/train.sh d3` to continue the second stage of training. 

I hope that helps!

**Comment by Hamza5** [comment]
Understood. Thank you for the explanation. I will try that.

**Comment by Hamza5** [comment]
Another error is happening now when the progress reaches 22% of the first epoch, _when I train on my dataset_. The traceback is as follows:

    [INFO] Training Model: tashkeela-d2
    Training: Epoch [0/100], Loss: 0.4006 | (509/2307):  22% 510/2.31k [08:07<28:28, 1.05it/s]/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [25,0,0] Assertion `t >= 0 && t < n_classes` failed.
    Traceback (most recent call last):
      File "train_d2.py", line 209, in <module>
        model.run()
      File "train_d2.py", line 142, in run
        train_loss = self.train(epi)
      File "train_d2.py", line 103, in train
        loss.backward()
      File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 221, in backward
        torch.autograd.backward(self, gradient, retain_graph, create_graph)
      File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 132, in backward
        allow_unreachable=True)  # allow_unreachable flag
    RuntimeError: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript (most recent call last):
      File "<string>", line 59, in fallback_function
                result = torch.sigmoid(self)
                def backward(grad_output):
                    return (1 - result) * result * grad_output
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

                return result, backward
    RuntimeError: CUDA error: device-side assert triggered

This error doesn't happen when I tried to use the dataset that you have used. So it seems that your code doesn't support some characters or words in the new dataset, even though I have run all the preprocessing steps (`segment_train_val.sh`, `segment_test.sh`, `embed_vocab.sh`). 

Do you have an idea of how to find the source of this problem and fix it? 

In case you need the dataset I use, [it is available here](https://www.kaggle.com/hamzaabbad/tashkeela-processed-fully-diacritized-arabic-text). Since it is a huge dataset, I only use the first 10 files from `tashkeela_train` folder (from `tashkeela_train_001.txt` to `tashkeela_train_010.txt`), and the first file from `tashkeela_val` folder (`tashkeela_val_001.txt`).

**Comment by Hamza5** [comment]
Nevermind, it seems that I have solved it by increasing `max-word-len` [as mentioned in this issue comment](https://github.com/BKHMSI/deep-diacritization/issues/3#issuecomment-735295331).

**Comment by Hamza5** [comment]
It seems that it is still not solved. I have just used a subset of my training data when I said that it was solved. But I am still having the same issue, and I have no experience with PyTorch (I use Tensorflow only), which makes debugging this really hard for me. Any help would be appreciated.

**Comment by Hamza5** [comment]
When I run it on the CPU instead of the GPU, it gives a clearer error traceback:

    [INFO] Training Model: tashkeela-d2
    Training: Epoch [0/100], Loss: 0.4008 | (509/2307):  22% 510/2.31k [5:10:10<18:46:43, 37.6s/it]Traceback (most recent call last):
      File "train_d2.py", line 209, in <module>
        model.run()
      File "train_d2.py", line 142, in run
        train_loss = self.train(epi)
      File "train_d2.py", line 102, in train
        loss = self.model.step(inputs, outputs, None)
      File "/content/drive/My Drive/Deep-diacritization/model_d2.py", line 166, in step
        loss = self.closs(diac.view(-1, self.num_classes), yt.view(-1))
      File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2468, in cross_entropy
        return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
      File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2264, in nll_loss
        ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
    IndexError: Target 15 is out of bounds.

I noticed that the number of classes (`num_classes`) was hardcoded in `model_d2.py` to the value of `15`, so the quickest solution for me was to increment it to `16`. _Not the ideal solution for sure, but at least I can train the model now._
